production:
  server: platform-science.amee.com
  username: 
  password: 
  cache: rails

development:
  server: platform-science.amee.com
  username:
  password:
  cache: rails

test:
  server: platform-science.amee.com
  username: 
  password: 